# Generated by Django 5.2.17 on 2026-09-19 05:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('checked', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=600, unique=True)),
                ('publisher', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('protocol', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('text', 'Текст и код'), ('image', 'Изображения'), ('video', 'Видео'), ('audio', 'Аудио'), ('other', 'Другие')], max_length=10)),
                ('unit', models.CharField(default='%', max_length=40)),
                ('higher_is_better', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'protocol'), name='unique_protocol')],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('text', 'Текст и код'), ('image', 'Изображения'), ('video', 'Видео'), ('audio', 'Аудио'), ('other', 'Другие')], max_length=10)),
                ('tasks', models.JSONField(default=list, help_text='Task keys: coding, documents, reasoning, images, video, audio, translation')),
                ('description', models.JSONField(default=dict, help_text='{"ru": "Описание", "en": "Description"}')),
                ('suitable', models.JSONField(default=dict)),
                ('limitations', models.JSONField(default=dict)),
                ('origin', models.JSONField(blank=True, default=dict)),
                ('philosophy', models.JSONField(blank=True, default=dict)),
                ('context', models.PositiveIntegerField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('open_weights', models.BooleanField(default=False)),
                ('checked', models.DateField()),
                ('published', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.modelfamily')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modelversion')),
            ],
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.organization'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entity', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.modelversion')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('api', 'API'), ('web', 'Сервис'), ('download', 'Скачать')], max_length=10)),
                ('url', models.URLField(max_length=600)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('input', '1M входных токенов'), ('output', '1M выходных токенов'), ('image', 'изображение'), ('megapixel', 'мегапиксель'), ('second', 'секунда видео'), ('minute', 'минута аудио'), ('month', 'месяц')], max_length=10)),
                ('conditions', models.JSONField(default=dict)),
                ('checked', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('primary', models.BooleanField(default=False, help_text='Display in the catalog; select one coherent provider/tier.')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.modelversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
            options={
                'ordering': ['unit', 'amount', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('modalities', 'Форматы'), ('languages', 'Языки'), ('speed', 'Скорость'), ('memory', 'Память и оборудование'), ('energy', 'Энергопотребление'), ('training', 'Обучение'), ('ownership', 'Владение и финансирование'), ('service_price', 'Цена сервиса')], max_length=25)),
                ('value', models.JSONField(default=dict)),
                ('checked', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=12)),
                ('evaluator', models.CharField(max_length=140)),
                ('independent', models.BooleanField(default=False)),
                ('measured', models.DateField(blank=True, null=True)),
                ('conditions', models.JSONField(default=dict)),
                ('checked', models.DateField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.benchmark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='catalog.modelversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelfamily',
            constraint=models.UniqueConstraint(fields=('name', 'developer'), name='unique_family'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(fields=('model', 'key'), name='unique_fact'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('model', 'benchmark'), name='one_result_per_protocol'),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(fields=('model', 'service'), name='unique_access'),
        ),
    ]
