# Generated by Django 5.2.17 on 2026-09-19 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def add_categories(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    rows = [
        ("text", {"ru": "Текст", "en": "Text"}),
        ("code", {"ru": "Код", "en": "Coding"}),
        ("reasoning", {"ru": "Рассуждения", "en": "Reasoning"}),
        ("image_generation", {"ru": "Изображения", "en": "Images"}),
        ("video_generation", {"ru": "Видео", "en": "Video"}),
        ("speech", {"ru": "Аудио и речь", "en": "Audio and speech"}),
        ("search", {"ru": "Поиск и данные", "en": "Search and data"}),
        ("specialized", {"ru": "Специализированные", "en": "Specialized"}),
    ]
    for position, (code, labels) in enumerate(rows):
        Category.objects.get_or_create(code=code, defaults={"labels": labels, "position": position})


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('labels', models.JSONField(default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('batch', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('review_required', 'Требует проверки'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='review_required', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelversion',
            name='entry_type',
            field=models.CharField(choices=[('model', 'Модель'), ('product', 'Продукт'), ('api_service', 'API-сервис'), ('runtime', 'Среда запуска')], default='model', max_length=16),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='input_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='output_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='translations_need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='compute_location',
            field=models.CharField(blank=True, choices=[('local', 'Устройство'), ('cloud', 'Облако'), ('hybrid', 'Гибрид')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='unit',
            field=models.CharField(choices=[('input', '1M входных токенов'), ('output', '1M выходных токенов'), ('image', 'изображение'), ('megapixel', 'мегапиксель'), ('second', 'секунда видео'), ('minute', 'минута аудио'), ('month', 'месяц'), ('year', 'год'), ('hour', 'час'), ('request', 'запрос'), ('credit', 'кредит'), ('cache_read', '1M токенов чтения кэша'), ('cache_write', '1M токенов записи кэша')], max_length=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('api', 'API'), ('web', 'Сайт'), ('download', 'Локально'), ('app', 'Приложение'), ('cli', 'CLI'), ('ide', 'Расширение IDE')], max_length=10),
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor', models.CharField(max_length=180)),
                ('scope', models.JSONField(default=dict)),
                ('version', models.CharField(max_length=150)),
                ('period', models.CharField(blank=True, max_length=150)),
                ('method', models.JSONField(default=dict)),
                ('conclusions', models.JSONField(default=dict)),
                ('checked', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
        ),
        migrations.RunPython(add_categories, migrations.RunPython.noop),
    ]
