# Generated by Django 5.2.17 on 2026-09-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_researchrecord_modelversion_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrecord',
            name='source_record_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ResearchRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.researchrecord')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
