# Generated by Django 5.2.17 on 2026-09-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_backfill_research_source_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='research_entity_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='billing_unit',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='offer',
            name='research_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='review_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='PublicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=30)),
                ('source_record_ids', models.JSONField(default=list)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_revisions', to='catalog.modelversion')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
