# Generated by Django 5.2.17 on 2026-09-22 00:16

import django.db.models.deletion
from django.db import migrations, models


COUNTRIES = {
    "AE": ("ОАЭ", "United Arab Emirates"),
    "CA": ("Канада", "Canada"),
    "CH": ("Швейцария", "Switzerland"),
    "CN": ("Китай", "China"),
    "DE": ("Германия", "Germany"),
    "FR": ("Франция", "France"),
    "GB": ("Великобритания", "United Kingdom"),
    "IN": ("Индия", "India"),
    "KR": ("Южная Корея", "South Korea"),
    "RU": ("Россия", "Russia"),
    "SG": ("Сингапур", "Singapore"),
    "US": ("США", "United States"),
}

# Only organizations with a direct, attributable country source are included.
# ai-sage remains blank because the current source does not establish an
# organization/country identity. ElevenLabs is intentionally multi-country.
ORIGIN_EVIDENCE = {
    "AI Singapore": (["SG"], "https://aisingapore.org/"),
    "Anthropic": (["US"], "https://www.anthropic.com/company"),
    "Black Forest Labs": (["DE"], "https://blackforestlabs.ai/about-us/"),
    "ByteDance": (["CN"], "https://www.bytedance.com/en/"),
    "Cohere Labs": (["CA"], "https://cohere.com/about"),
    "DeepSeek": (["CN"], "https://www.deepseek.com/"),
    "ElevenLabs": (["US", "GB"], "https://elevenlabs.io/blog/eu-ai-champions"),
    "Google": (["US"], "https://about.google/company-info/"),
    "LG AI Research": (["KR"], "https://www.lgresearch.ai/"),
    "Meta": (["US"], "https://about.meta.com/company-info/"),
    "Microsoft": (["US"], "https://www.microsoft.com/en-us/about"),
    "MiniMax": (["CN"], "https://www.minimax.io/about"),
    "Mistral AI": (["FR"], "https://mistral.ai/company"),
    "Moonshot AI": (["CN"], "https://www.moonshot.cn/"),
    "NVIDIA": (["US"], "https://www.nvidia.com/en-us/about-nvidia/"),
    "OpenAI": (["US"], "https://openai.com/about/"),
    "Qwen / Alibaba": (["CN"], "https://www.alibabagroup.com/en-US/about-alibaba"),
    "Runway": (["US"], "https://runwayml.com/about"),
    "Sarvam AI": (["IN"], "https://www.sarvam.ai/"),
    "SpaceXAI / xAI (����� ������������)": (["US"], "https://x.ai/company"),
    "Stability AI": (["GB"], "https://stability.ai/about"),
    "Swiss AI Initiative": (["CH"], "https://www.swiss-ai.org/"),
    "Technology Innovation Institute": (["AE"], "https://www.tii.ae/insights/inside-falcon-uaes-open-source-model-challenging-ai-giants"),
    "Tencent": (["CN"], "https://www.tencent.com/en-us/about.html"),
    "Wan-AI": (["CN"], "https://www.alibabagroup.com/en-US/about-alibaba"),
    "Yandex": (["RU"], "https://yandex.com/company/"),
    "Z.ai / Zhipu AI": (["CN"], "https://www.zhipuai.cn/en"),
}

TOOL_CATEGORIES = {
    "ChatGPT": "ai_app",
    "Claude": "ai_app",
    "Claude Code": "coding_agent",
    "Codex": "coding_agent",
    "Cursor": "ide_tool",
    "Gemini CLI": "coding_agent",
    "GitHub Copilot": "coding_assistant",
    "LM Studio / Bionic": "client",
    "Midjourney": "creative_app",
    "Ollama": "runtime",
    "Suno": "creative_app",
}

TOOL_ECOSYSTEMS = {
    "ChatGPT": {"ru": "Модели OpenAI", "en": "OpenAI models"},
    "Claude": {"ru": "Модели Claude", "en": "Claude models"},
    "Claude Code": {"ru": "Модели Claude", "en": "Claude models"},
    "Codex": {"ru": "Модели OpenAI", "en": "OpenAI models"},
    "Cursor": {"ru": "Модели разных разработчиков", "en": "Models from multiple providers"},
    "Gemini CLI": {"ru": "Модели Gemini", "en": "Gemini models"},
    "GitHub Copilot": {"ru": "Модели разных разработчиков", "en": "Models from multiple providers"},
    "LM Studio / Bionic": {"ru": "Локальные модели с открытыми весами", "en": "Local open-weight models"},
    "Midjourney": {"ru": "Экосистема Midjourney", "en": "Midjourney ecosystem"},
    "Ollama": {"ru": "Llama, Qwen, Gemma и другие модели", "en": "Llama, Qwen, Gemma, and other models"},
    "Suno": {"ru": "Экосистема Suno", "en": "Suno ecosystem"},
}

PLATFORMS = {
    "web": ({"ru": "Web", "en": "Web"}, 10),
    "desktop": ({"ru": "Desktop", "en": "Desktop"}, 15),
    "mobile": ({"ru": "Mobile", "en": "Mobile"}, 18),
    "windows": ({"ru": "Windows", "en": "Windows"}, 20),
    "macos": ({"ru": "macOS", "en": "macOS"}, 30),
    "linux": ({"ru": "Linux", "en": "Linux"}, 40),
    "ios": ({"ru": "iOS", "en": "iOS"}, 50),
    "android": ({"ru": "Android", "en": "Android"}, 60),
    "cli": ({"ru": "CLI", "en": "CLI"}, 70),
    "ide": ({"ru": "IDE", "en": "IDE"}, 80),
    "api": ({"ru": "API", "en": "API"}, 90),
}


def split_catalog_data(apps, schema_editor):
    from datetime import date

    Country = apps.get_model("catalog", "Country")
    ModelOriginCountry = apps.get_model("catalog", "ModelOriginCountry")
    ModelVersion = apps.get_model("catalog", "ModelVersion")
    Platform = apps.get_model("catalog", "Platform")
    PublicationRevision = apps.get_model("catalog", "PublicationRevision")
    Source = apps.get_model("catalog", "Source")
    Tool = apps.get_model("catalog", "Tool")
    ToolPlatform = apps.get_model("catalog", "ToolPlatform")
    ToolPublicationRevision = apps.get_model("catalog", "ToolPublicationRevision")
    using = schema_editor.connection.alias
    checked = date(2026, 9, 21)

    for code, (name_ru, name_en) in COUNTRIES.items():
        Country.objects.using(using).update_or_create(
            code=code, defaults={"name_ru": name_ru, "name_en": name_en}
        )

    for model in ModelVersion.objects.using(using).filter(entry_type="model"):
        developer_name = model.family.developer.name
        evidence = ORIGIN_EVIDENCE.get(developer_name)
        if not evidence and developer_name.startswith("SpaceXAI / xAI"):
            evidence = (["US"], "https://x.ai/company")
        if not evidence:
            continue
        codes, url = evidence
        source, _ = Source.objects.using(using).get_or_create(
            url=url,
            defaults={
                "title": f"{model.family.developer.name} organization profile",
                "publisher": model.family.developer.name[:120],
            },
        )
        for position, code in enumerate(codes):
            ModelOriginCountry.objects.using(using).get_or_create(
                model=model,
                country_id=code,
                defaults={"source": source, "checked": checked, "position": position},
            )

    platforms = {}
    for code, (labels, position) in PLATFORMS.items():
        platforms[code], _ = Platform.objects.using(using).update_or_create(
            code=code, defaults={"labels": labels, "position": position}
        )

    tools = []
    for legacy in ModelVersion.objects.using(using).exclude(entry_type="model").order_by("pk"):
        services = list(legacy.accesses.select_related("service", "source").all())
        category = TOOL_CATEGORIES.get(
            legacy.name,
            "runtime" if legacy.entry_type == "runtime" else "api_service",
        )
        official_url = services[0].service.url if services else legacy.source.url
        locations = {item.service.compute_location for item in services if item.service.compute_location}
        if locations and locations <= {"cloud"}:
            local_execution = "no"
        elif locations & {"local", "hybrid", "configuration_dependent"}:
            local_execution = "hybrid"
        else:
            local_execution = ""
        tool = Tool.objects.using(using).create(
            legacy_version=legacy,
            name=legacy.name,
            slug=legacy.slug,
            version=legacy.version,
            developer=legacy.family.developer,
            category=category,
            purposes=legacy.tasks,
            description=legacy.description,
            ecosystem=TOOL_ECOSYSTEMS.get(legacy.name, {}),
            local_execution=local_execution,
            official_url=official_url,
            released=legacy.released,
            release_evidence=legacy.release_evidence,
            source=legacy.source,
            checked=legacy.checked,
            published=legacy.published,
            catalog_status=legacy.catalog_status,
        )
        tools.append(tool)
        codes = set()
        for access in services:
            kind = access.service.kind
            if kind in {"web", "cli", "ide", "api"}:
                codes.add(kind)
            elif kind == "download":
                codes.add("desktop")
            elif kind == "app":
                label = access.service.name.casefold()
                if "mobile" in label:
                    codes.add("mobile")
                else:
                    codes.add("desktop")
        for code in sorted(codes, key=lambda item: PLATFORMS[item][1]):
            access = next(
                (
                    item
                    for item in services
                    if item.service.kind == code
                    or code in {"desktop", "mobile"}
                ),
                None,
            )
            ToolPlatform.objects.using(using).get_or_create(
                tool=tool,
                platform=platforms[code],
                defaults={
                    "source": access.source if access else legacy.source,
                    "checked": access.checked if access else legacy.checked,
                },
            )

    # Independent chronological sequences. Unknown dates stay unnumbered.
    model_rows = list(ModelVersion.objects.using(using).filter(entry_type="model"))
    model_numbers = {
        item.pk: number
        for number, item in enumerate(
            sorted(
                (item for item in model_rows if item.published and item.released),
                key=lambda item: (item.released, item.name.casefold(), item.slug),
            ),
            1,
        )
    }
    for item in ModelVersion.objects.using(using).all():
        old = item.public_number
        new = model_numbers.get(item.pk) if item.entry_type == "model" else None
        if old == new:
            continue
        ModelVersion.objects.using(using).filter(pk=item.pk).update(public_number=None)
        if item.entry_type == "model":
            PublicationRevision.objects.using(using).create(
                entity_id=item.research_entity_id or item.slug,
                model=item,
                action="split_catalog_renumber",
                before={"public_number": old},
                after={"public_number": new, "catalog": "models"},
            )
    for pk, number in model_numbers.items():
        ModelVersion.objects.using(using).filter(pk=pk).update(public_number=number)

    tool_numbers = {
        item.pk: number
        for number, item in enumerate(
            sorted(
                (item for item in tools if item.published and item.released),
                key=lambda item: (item.released, item.name.casefold(), item.slug),
            ),
            1,
        )
    }
    for item in tools:
        number = tool_numbers.get(item.pk)
        Tool.objects.using(using).filter(pk=item.pk).update(public_number=number)
        if number is not None:
            ToolPublicationRevision.objects.using(using).create(
                tool=item,
                action="split_catalog_number",
                before={"public_number": None},
                after={"public_number": number, "catalog": "tools"},
            )


def reverse_split_catalog_data(apps, schema_editor):
    # Schema rollback drops the new normalized tables. Restore the historical
    # single-sequence numbers so a rollback remains usable.
    ModelVersion = apps.get_model("catalog", "ModelVersion")
    using = schema_editor.connection.alias
    rows = list(ModelVersion.objects.using(using).all())
    numbered = sorted(
        (item for item in rows if item.published and item.released),
        key=lambda item: (item.released, item.name.casefold(), item.slug),
    )
    ModelVersion.objects.using(using).all().update(public_number=None)
    for number, item in enumerate(numbered, 1):
        ModelVersion.objects.using(using).filter(pk=item.pk).update(public_number=number)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_release_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('labels', models.JSONField(default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='catalog_status',
            field=models.CharField(choices=[('active', 'Активна'), ('deprecated', 'Deprecated'), ('retired', 'Снята'), ('archived', 'Архив')], default='active', max_length=12),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('ai_app', 'AI-приложение'), ('coding_assistant', 'Coding assistant'), ('coding_agent', 'Coding agent'), ('runtime', 'Runtime'), ('api_platform', 'API-платформа'), ('api_service', 'API-сервис'), ('ide_tool', 'IDE-инструмент'), ('client', 'Клиент / интерфейс'), ('agent_platform', 'Agent platform'), ('creative_app', 'Творческое AI-приложение')], max_length=24)),
                ('purposes', models.JSONField(blank=True, default=list)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('ecosystem', models.JSONField(blank=True, default=dict)),
                ('local_execution', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('hybrid', 'Гибрид')], max_length=8)),
                ('official_url', models.URLField(blank=True, max_length=600)),
                ('released', models.DateField(blank=True, null=True)),
                ('release_evidence', models.JSONField(blank=True, default=dict)),
                ('checked', models.DateField()),
                ('published', models.BooleanField(default=True)),
                ('public_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('catalog_status', models.CharField(choices=[('active', 'Активна'), ('deprecated', 'Deprecated'), ('retired', 'Снята'), ('archived', 'Архив')], default='active', max_length=12)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='catalog.organization')),
                ('legacy_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_record', to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolModelSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.DateField()),
                ('note', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_links', to='catalog.tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='supported_models',
            field=models.ManyToManyField(related_name='supported_by_tools', through='catalog.ToolModelSupport', to='catalog.modelversion'),
        ),
        migrations.CreateModel(
            name='ToolPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.DateField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.platform')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='catalog.tool')),
            ],
            options={
                'ordering': ['platform__position', 'platform__code'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='platforms',
            field=models.ManyToManyField(related_name='tools', through='catalog.ToolPlatform', to='catalog.platform'),
        ),
        migrations.CreateModel(
            name='ToolPublicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_revisions', to='catalog.tool')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ModelOriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.DateField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='catalog.country')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_country_links', to='catalog.modelversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
            options={
                'ordering': ['position', 'country__code'],
                'constraints': [models.UniqueConstraint(fields=('model', 'country'), name='unique_model_origin_country')],
            },
        ),
        migrations.AddConstraint(
            model_name='toolmodelsupport',
            constraint=models.UniqueConstraint(fields=('tool', 'model'), name='unique_tool_model_support'),
        ),
        migrations.AddConstraint(
            model_name='toolplatform',
            constraint=models.UniqueConstraint(fields=('tool', 'platform'), name='unique_tool_platform'),
        ),
        migrations.RunPython(split_catalog_data, reverse_split_catalog_data),
    ]
