# Generated by Django 5.2.17 on 2026-09-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_global_catalog_20260922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=12)),
                ('source_hash', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('current', 'Current'), ('outdated', 'Outdated'), ('missing', 'Missing'), ('reviewed', 'Reviewed')], default='missing', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'object_id'], name='catalog_con_entity__05212f_idx'), models.Index(fields=['state'], name='catalog_con_state_1b2331_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'object_id', 'field', 'language'), name='unique_content_translation')],
            },
        ),
    ]
