# Generated by Django 5.2.17 on 2026-09-24 02:15

from django.db import migrations, models


def _assign_permanent_numbers(apps, schema_editor):
    """Fill every published Model/Tool that still lacks a permanent number.

    Existing numbers are preserved; remaining published rows are numbered once,
    deterministically (by name, then slug), continuing each sequence from its
    current maximum. Numbers are never recomputed afterwards.
    """
    from catalog.comparison import alphabet

    db = schema_editor.connection.alias
    ModelVersion = apps.get_model('catalog', 'ModelVersion')
    PublicationRevision = apps.get_model('catalog', 'PublicationRevision')
    Tool = apps.get_model('catalog', 'Tool')
    ToolPublicationRevision = apps.get_model('catalog', 'ToolPublicationRevision')

    def fill(queryset, start, make_revision):
        ordered = sorted(queryset, key=lambda o: (alphabet(o.name), o.slug))
        for offset, obj in enumerate(ordered, 1):
            obj.public_number = start + offset
            obj.save(update_fields=['public_number'])
            make_revision(obj)

    model_qs = ModelVersion.objects.using(db).filter(
        entry_type='model', published=True, public_number__isnull=True)
    if model_qs.exists():
        model_start = ModelVersion.objects.using(db).filter(entry_type='model').exclude(
            public_number__isnull=True).order_by('-public_number').values_list(
            'public_number', flat=True).first() or 0
        fill(list(model_qs), model_start, lambda m: PublicationRevision.objects.using(db).create(
            model=m, entity_id=m.research_entity_id or m.slug,
            action='assign_catalog_number', before={'public_number': None},
            after={'public_number': m.public_number, 'identity': m.slug}))

    tool_qs = Tool.objects.using(db).filter(published=True, public_number__isnull=True)
    if tool_qs.exists():
        tool_start = Tool.objects.using(db).exclude(public_number__isnull=True).order_by(
            '-public_number').values_list('public_number', flat=True).first() or 0
        fill(list(tool_qs), tool_start, lambda t: ToolPublicationRevision.objects.using(db).create(
            tool=t, action='assign_catalog_number', before={'public_number': None},
            after={'public_number': t.public_number, 'identity': t.slug}))


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_contenttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='approx_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='approx_precision',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='approx_released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='approx_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tool',
            name='approx_precision',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='tool',
            name='approx_released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(_assign_permanent_numbers, _noop),
    ]
