# Generated by Django 5.2.17 on 2026-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_approx_dates_and_permanent_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='release_stage',
            field=models.CharField(blank=True, choices=[('released', 'Released'), ('preview', 'Preview'), ('beta', 'Beta'), ('research', 'Research')], default='', max_length=10),
        ),
    ]
