# Generated by Django 5.2.17 on 2026-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_release_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600)),
                ('lang', models.CharField(blank=True, max_length=12)),
                ('entity_kind', models.CharField(blank=True, max_length=12)),
                ('record_id', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('upsert', 'Created or updated'), ('remove', 'Removed')], max_length=10)),
                ('reason', models.CharField(max_length=40)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created', 'pk'],
                'indexes': [models.Index(fields=['state', 'next_attempt'], name='catalog_dis_state_b2a0bc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('url',), name='one_pending_event_per_url')],
            },
        ),
    ]
