# Generated by Django 5.2.17 on 2026-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_discovery_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='redirect_to',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tool',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='redirect_to',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
